on: [push]

jobs:
  getversion_job:
    runs-on: ubuntu-latest
    name: A job to get my version
    steps:
    - uses: actions/checkout@v1
    - name: Calculate Version
      id: gitversion
      uses: zentron/github-actions@master
    - name: Print Version Details
      run: echo "The version is ${GITVERSION_InformationalVersion} ${{ steps.gitversion.outputs.version }}"